language: bash
services: docker
before_install:
  - cd 17\ RestWithSpringBoot\ Docker/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push lfelipe1993/mysql-rest-with-spring-boot;
    docker push lfelipe1993/rest-with-spring-boot;
  on:
    branch: master
notifications:
  email: false
